using UnityEngine;

public class XRP : MonoBehaviour
{
    // reads motor angle, opening and closing each vent from astrobee
    Astrobee astrobee;
    // reads acceleration data from IMU
    IMU imu;

    // Actual acceleration and linear acceleration generated by each vent 
    float[][] V;

    // computed position
    Vector3 position;
    // computed linear velocity
    Vector3 velocity;
    // computed orientation
    Vector3 orientation;
    // computed angular velocity 
    Vector3 angularVelocity;


    void Start()
    {
        // Look for the Astrobee component in this GameObject
        astrobee = GetComponent<Astrobee>();

        // Check if the component was found
        if (astrobee == null)
        {
            Debug.LogError("Astrobee component not found on this GameObject.");
        }

        // Look for the IMU component in this GameObject
        imu = GetComponent<IMU>();

        // Check if the component was found
        if (imu == null)
        {
            Debug.LogError("IMU component not found on this GameObject.");
        }
        InitializeV();
    }

    // Update is called once per frame
    void Update()
    {

    }

    // initialize V by the data given in Parameters
    void InitializeV()
    {

    }

}
